name: Go Build & Test
on: 
  push:
    paths:
      - '**.go'
      - '**.yaml'
      - '**.yml'
      - '**.sql'      
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Build & Test
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Remove windows dependencies for Ubuntu
      if: runner.os == 'Linux'
      run: |
        rm -r iphlpapi

    - name: Run Revive Action by pulling pre-built image
      uses: docker://morphy/revive-action:v2
      with:
        config: revive.toml
        exclude: "iphlpapi;package;test"

    - name: Get dependencies
      run: |
        go mod download
        go version
        go build
